import '../globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

// ✅ Make the layout async
export default async function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <div className="flex min-h-screen w-full">
          {/* Left Panel with image background */}
          <div
            className="hidden lg:flex items-center justify-center w-1/2 px-12 bg-cover bg-center  bg-black bg-opacity-50 p-6"
          >
            <div className="max-w-md space-y-6 text-center text-white bg-black bg-opacity-50 p-6 rounded-lg">
              <h1 className="text-4xl font-extrabold tracking-tight">
                Welcome to X
              </h1>
            </div>
          </div>

          {/* Right Panel */}
          <div className="flex flex-1 items-center justify-center bg-background px-4 py-12 sm:px-6 lg:px-8">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
